### PR TITLE
Origin

### PR DESCRIPTION
**Pull request by NicholasTurner23**
made the contacts unique. They are now only entered once.

### CODE REVIEW

**Comment by xkmato** [comment]
Why does the branch have conflicts? Please resolve those

**Comment by NicholasTurner23** [comment]
The conflicts have been resolved.

**Comment by NicholasTurner23** [comment]
added async tasks, updated model so that it doesn't complain if there are no files to synchronize, now can differentiate between 24hour time saving and 12 hour time saving, updated readme.

**Comment by xkmato** [comment]
Good job, will look at this today and merge tomorrow morning when we meet

**Pull request merged**
